config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts
      end
    end
  end

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5}, presence: true
  validates :user, presence: true

  default_scope { order('updated_at ASC') }

  after_create :send_favorite_emails

  private

    def send_favorite_emails
      post.favorites.each do |favorite|
        FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
      end
    end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?

    label_string.split(",").map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end

end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :votes, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :labelings, as: :labelable
	has_many :labels, through: :labelings

	default_scope { order('rank DESC') }
	scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

	validates :title, length: { minimum: 5 }, presence: true
	validates :body, length: { minimum: 20 }, presence: true
	validates :topic, presence: true
	validates :user, presence: true

	def up_votes
		self.votes.where(value: 1).count
	end

	def down_votes
		self.votes.where(value: -1).count
	end

	def points
		votes.sum(:value)
	end

	def update_rank
		age_in_days = (created_at - Time.new(1970, 1,1)) / 1.day.seconds
		new_rank = points + age_in_days
		update_attribute(:rank, new_rank)
	end

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  enum severity: { PG: 0, PG13: 1, R: 2 }
  has_many :posts
  has_many :topics

  def self.update_rating(rating_string)
    if rating_string.present?
      rating = Rating.where(severity: rating_string.to_i).first_or_create
    else
      rating = Rating.where(severity: 'R').first_or_create
    end
    rating
  end

end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
	belongs_to :topic, dependent: :destroy
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts, dependent: :destroy

	has_many :labelings, as: :labelable
	has_many :labels, through: :labelings

	scope :publicly_viewable, -> { where(public: true) }
	scope :privately_viewable, -> { where(public: false) }
	scope :visible_to, -> (user) { user ? all : publicly_viewable }
=begin
	def visible_to(user)
		if user
			Topics.all
		else
			Topics.where(public: true)
		end
	end
=end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save { self.role ||= :member }
  before_create :generate_auth_token

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100}, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6}, allow_blank: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 100 },
            format: { with: EMAIL_REGEX }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [1, -1], message: "%{value} is not a valid vote."}, presence: true

  private
  def update_post
    post.update_rank
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper

  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

  def user_is_a_moderator?
    current_user && current_user.moderator?
  end
  
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end

  def user_is_a_moderator?
    current_user && current_user.moderator?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_has_got_posts?(user)
    user.posts.count > 0
  end

  def user_has_got_comments?(user)
    user.comments.count > 0
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome to <%= link_to 'Bloccit', root_path, title: "Back to home page." %></h1>
<br>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6">
      <h2>Sign up is simple and secure</h2>
      <ol>
        <li>
          Fill the <%= link_to 'sign up form', new_user_path, title: '' %> with a <strong>user name</strong>, <strong>your email address</strong> and a <strong>password</strong>.
        </li>
      </ol>
      <p class="lead">
        <small>
          We won't store your data or give them to anybody.
        </small>
      </p>
    </div>

    <div class="col-md-6">
      <h2>You do not feel comfortable and want to test Bloccit without sign up?</h2>
      <div class="row">
        <div class="col-md-6">
          <p>You can sign in as the member demo user.</p>
          <ul>
            <li>user: <em>member@example.com</em></li>
            <li>password: <em>helloworld</em></li>
          </ul>
        </div>
        <div class="col-md-6">
          <p>You can sign in as the premium demo user.</p>
          <ul>
            <li>user: <em>admin@example.com</em></li>
            <li>password: <em>helloworld</em></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<br />
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for post and comment about a variety of topics</p>
  <p>
    <%= link_to "Sign In", new_session_path, class: 'btn btn-success' %> or
    <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
  </p>
</div>
<div class="row">
  <div class="col-md-4">
    <h2>Not signed in ?!?</h2>
    <p>If you don't sign in you can only read.<br />If you want to create new posts and comments other users' posts you need to <%= link_to "sign up", new_user_path, title: "" %></p>
  </div>
  <div class="col-md-4">
    <h2>As a user you can...</h2>
    <ul>
      <li>Create posts on topics you like.</li>
      <li>Comment other users' posts.</li>
      <li>Favorite posts you like the most and receive email notifications every time other users comment on them.</li>
    </ul>
  </div>
  <div class="col-md-4">
    <h2>If you want to test...</h2>
    <ul>
      <li>You can <%= link_to 'sign up', new_user_path, title: '' %> or</li>
      <li>use our <strong> <%= link_to "demo users", about_path, title: '' %> </strong></li>
    </ul>
  </div>
</div>